# mkdocs.yml

# -------------------------------------------------------------
# CONFIGURACIÓN GENERAL DEL SITIO
# -------------------------------------------------------------
site_name: PPS-Unidad-Tarea-PPS # Define el título que aparecerá en la barra de navegación y en la etiqueta <title> del navegador.

# -------------------------------------------------------------
# ESTRUCTURA DE NAVEGACIÓN (MENÚ)
# -------------------------------------------------------------
# Define la lista de enlaces y el orden de aparición en el menú de navegación principal.
nav:
  # El nombre de la sección en el menú: nombre_archivo.md
  - Home: index.md             # Primer elemento del menú, enlaza con el archivo 'index.md'.
  - Git: git.md           # Segundo elemento del menú, enlaza con el archivo 'guia_uso.md'.
  - GitActions: gitActions.md
  - GitPages: gitPages.md
  - Docker: docker.md
  - Conclusiones: conclusiones.md
  - Otros: otros.md

# -------------------------------------------------------------
# DIRECTORIOS
# -------------------------------------------------------------
# Ruta de la carpeta que contiene todos los archivos .md (Markdown) de la documentación.
# MkDocs buscará aquí los archivos listados en 'nav'.
doc_dir: docs 
